export const CONFIG = {
  API_TIMEOUT: 10000,
  PRODUCTS_PER_PAGE: 12,
  ACCESS_TOKEN_MAX_AGE: 60 * 60,
  REFRESH_TOKEN_MAX_AGE: 60 * 60 * 24 * 7,
  MIN_USERNAME_LENGTH: 3,
  MIN_PASSWORD_LENGTH: 3,
} as const;
